name: WebConsoleServer
authors: [ Maxlego08 ]
main: fr.maxlego08.console.spigot.WebServerPlugin
description: Console for your server
website: https://groupez.dev/server
version: ${version}
load: STARTUP
